[profile.default]
src = "src"
out = "out"
libs = ["lib"]




# Sepolia testnet RPC
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan for verification
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
